repos:
  - repo: https://github.com/syntaqx/git-hooks 
    rev: v0.0.17
    hooks:
    - id: shellcheck
    - id: go-fmt
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 4.0.1.1
    hooks:
      - id: buildifier
        args: &args
          # Keep this argument in sync with .bazelci/presubmit.yaml
          - --warnings=all
      - id: buildifier-lint
        args: *args