name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel action cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Mount bazel repo cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel-repo"
          key: bazel-repo
      - name: bazel test //...
        env:
          # Bazelisk will download bazel to here
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: bazel --config=release --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bazel-out/*-opt-*/bin/cmd/aspect/aspect-linux_amd64
            bazel-out/*-opt-*/bin/cmd/aspect/aspect-linux_arm64
            bazel-out/*-opt-*/bin/cmd/aspect/aspect-darwin_amd64
            bazel-out/*-opt-*/bin/cmd/aspect/aspect-darwin_arm64
            bazel-out/*-opt-*/bin/cmd/aspect/aspect-windows_amd64.exe